# Generated by Django 3.0.8 on 2020-07-09 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study',
        ),
    ]
